import { Category, MenuItem, InventoryItem, Order, User } from './types';
import { APP_CONFIG } from './config';

export const initialCategories: Category[] = [
  { id: 'cat-1', name: 'slow mornings', description: 'coffee & morning comfort', order: 1 },
  { id: 'cat-2', name: 'chai, chaas & good decisions', description: 'brews, chais & chillas', order: 2 },
  { id: 'cat-3', name: 'got the munchies?', description: 'toasts, dips & light bites', order: 3 },
  { id: 'cat-4', name: 'i need actual food', description: 'bowls, pastas & heartier plates', order: 4 },
  { id: 'cat-5', name: 'we did something weird', description: 'experimental brews & house specials', order: 5 },
  { id: 'cat-6', name: 'sweet conclusions', description: 'baked goods & quiet desserts', order: 6 },
];

export const initialMenuItems: MenuItem[] = [
  {
    id: 'item-1',
    name: 'Tapovan Pour Over',
    categoryId: 'cat-1',
    price: 180,
    description: 'Single-origin South Indian estate beans, light floral notes',
    available: true,
    isVeg: true,
    isSpecial: true,
    image: '/item-pourover.png',
  },
  {
    id: 'item-2',
    name: 'Smol Espresso',
    categoryId: 'cat-1',
    price: 120,
    description: 'Double shot, rich dark chocolate notes & thick crema',
    available: true,
    isVeg: true,
    image: '/item-espresso.png',
  },
  {
    id: 'item-3',
    name: 'Oat Milk Flat White',
    categoryId: 'cat-1',
    price: 210,
    description: 'Creamy microfoam oat milk over velvety espresso',
    available: true,
    isVeg: true,
    image: '/item-flatwhite.png',
  },
  {
    id: 'item-4',
    name: 'Himalayan Kulhad Masala Chai',
    categoryId: 'cat-2',
    price: 90,
    description: 'Brewed with lemongrass, ginger & green cardamom',
    available: true,
    isVeg: true,
    image: '/item-kulhadchai.png',
  },
  {
    id: 'item-14',
    name: 'Guava Chilli Fizz',
    categoryId: 'cat-5',
    price: 160,
    description: 'Pink guava, lime, chilli & a hint of mint',
    available: true,
    isVeg: true,
    image: '/item-guavafizz.png',
  },
  {
    id: 'item-5',
    name: 'mint & roasted cumin chaas',
    categoryId: 'cat-2',
    price: 110,
    description: 'chilled artisanal buttermilk topped with black salt',
    available: true,
    isVeg: true,
    image: '/item_chaas.jpg',
  },
  {
    id: 'item-6',
    name: 'avocado sourdough toast',
    categoryId: 'cat-3',
    price: 280,
    description: 'house-milled sourdough, smashed avocado, chilli flakes & seeds',
    available: true,
    isVeg: true,
    isSpecial: true,
    image: '/item_avocado.jpg',
  },
  {
    id: 'item-7',
    name: 'garlic butter mushroom sourdough',
    categoryId: 'cat-3',
    price: 260,
    description: 'pan-seared wild mushrooms with thyme on toasted sourdough',
    available: true,
    isVeg: true,
    image: '/item_mushroom.jpg',
  },
  {
    id: 'item-8',
    name: 'rishikesh green grain bowl',
    categoryId: 'cat-4',
    price: 340,
    description: 'quinoa, roasted chickpeas, kale, roasted pumpkin & tahini',
    available: true,
    isVeg: true,
    image: '/mood-light-card.png',
  },
  {
    id: 'item-9',
    name: 'smokey paneer pesto panini',
    categoryId: 'cat-4',
    price: 310,
    description: 'grilled cottage cheese, basil pesto & sun-dried tomatoes',
    available: true,
    isVeg: true,
    image: '/item_panini.jpg',
  },
  {
    id: 'item-10',
    name: 'rose cardamom cold tonic brew',
    categoryId: 'cat-5',
    price: 230,
    description: '12-hour cold brew infused with organic rose petals & tonic',
    available: true,
    isVeg: true,
    isSpecial: true,
    image: '/item_rosebrew.jpg',
  },
  {
    id: 'item-11',
    name: 'salted caramel espresso frappe',
    categoryId: 'cat-5',
    price: 240,
    description: 'blended espresso with house caramel & sea salt flakes',
    available: true,
    isVeg: true,
    image: '/mood-coffee-card.png',
  },
  {
    id: 'item-12',
    name: 'dark chocolate olive oil cake',
    categoryId: 'cat-6',
    price: 190,
    description: 'fudgy 70% dark chocolate slice served warm with vanilla cream',
    available: true,
    isVeg: true,
    image: '/item_chocolatecake.jpg',
  },
  {
    id: 'item-13',
    name: 'lemon & thyme tea cake',
    categoryId: 'cat-6',
    price: 150,
    description: 'moist citrus loaf slice with subtle herbal thyme undertones',
    available: true,
    isVeg: true,
    image: '/item_chocolatecake.jpg',
  },
];

// Calculate derived freshness
const today = new Date();
const formatDate = (daysOffset: number) => {
  const d = new Date();
  d.setDate(today.getDate() + daysOffset);
  return d.toISOString().split('T')[0];
};

export const initialInventoryItems: InventoryItem[] = [
  {
    id: 'inv-1',
    name: 'Single Origin Coffee Beans (South India)',
    quantity: 12.5,
    unit: 'kg',
    category: 'Coffee & Beverage',
    minThreshold: 5.0,
    dateAdded: formatDate(-10),
    expiryDate: formatDate(60),
    status: 'fresh',
  },
  {
    id: 'inv-2',
    name: 'Oat Milk (Barista Blend)',
    quantity: 8,
    unit: 'litres',
    category: 'Dairy & Alternatives',
    minThreshold: 10,
    dateAdded: formatDate(-3),
    expiryDate: formatDate(1),
    status: 'expiring_soon',
    notes: 'Use for flat whites and lattes today',
  },
  {
    id: 'inv-3',
    name: 'Fresh Lemongrass & Ginger',
    quantity: 1.2,
    unit: 'kg',
    category: 'Produce',
    minThreshold: 0.5,
    dateAdded: formatDate(-4),
    expiryDate: formatDate(2),
    status: 'expiring_soon',
  },
  {
    id: 'inv-4',
    name: 'Fresh Avocado (Hass)',
    quantity: 15,
    unit: 'pcs',
    category: 'Produce',
    minThreshold: 8,
    dateAdded: formatDate(-2),
    expiryDate: formatDate(3),
    status: 'fresh',
  },
  {
    id: 'inv-5',
    name: 'House Artisan Sourdough Loaves',
    quantity: 4,
    unit: 'loaves',
    category: 'Bakery',
    minThreshold: 5,
    dateAdded: formatDate(-1),
    expiryDate: formatDate(1),
    status: 'expiring_soon',
  },
  {
    id: 'inv-6',
    name: 'Organic Milk',
    quantity: 3,
    unit: 'litres',
    category: 'Dairy & Alternatives',
    minThreshold: 12,
    dateAdded: formatDate(-7),
    expiryDate: formatDate(-1),
    status: 'expired',
    notes: 'Marked for kitchen audit',
  },
  {
    id: 'inv-7',
    name: 'Fresh Basil & Mint Herbs',
    quantity: 0.8,
    unit: 'kg',
    category: 'Produce',
    minThreshold: 0.4,
    dateAdded: formatDate(-1),
    expiryDate: formatDate(4),
    status: 'fresh',
  },
];

export const initialOrders: Order[] = [
  {
    id: 'ord-101',
    orderNumber: 'SMOL-101',
    items: [
      { id: 'oi-1', menuItemId: 'item-1', name: 'tapovan pour over', price: 180, quantity: 2 },
      { id: 'oi-2', menuItemId: 'item-6', name: 'avocado sourdough toast', price: 280, quantity: 1 },
    ],
    subtotal: 640,
    discount: 0,
    tax: 32,
    total: 672,
    status: 'ready',
    paymentMethod: 'upi',
    orderType: 'dine_in',
    createdAt: new Date(Date.now() - 45 * 60000).toISOString(),
    updatedAt: new Date(Date.now() - 10 * 60000).toISOString(),
    cashierName: 'Priya',
  },
  {
    id: 'ord-102',
    orderNumber: 'SMOL-102',
    items: [
      { id: 'oi-3', menuItemId: 'item-4', name: 'himalayan kulhad masala chai', price: 90, quantity: 2 },
      { id: 'oi-4', menuItemId: 'item-12', name: 'dark chocolate olive oil cake', price: 190, quantity: 1 },
    ],
    subtotal: 370,
    discount: 0,
    tax: 18.5,
    total: 388.5,
    status: 'preparing',
    paymentMethod: 'cash',
    orderType: 'dine_in',
    createdAt: new Date(Date.now() - 20 * 60000).toISOString(),
    updatedAt: new Date(Date.now() - 15 * 60000).toISOString(),
    cashierName: 'Priya',
  },
  {
    id: 'ord-103',
    orderNumber: 'SMOL-103',
    items: [
      { id: 'oi-5', menuItemId: 'item-3', name: 'oat milk flat white', price: 210, quantity: 1 },
      { id: 'oi-6', menuItemId: 'item-7', name: 'garlic butter mushroom sourdough', price: 260, quantity: 1 },
    ],
    subtotal: 470,
    discount: 0,
    tax: 23.5,
    total: 493.5,
    status: 'received',
    paymentMethod: 'upi',
    orderType: 'takeaway',
    createdAt: new Date(Date.now() - 5 * 60000).toISOString(),
    updatedAt: new Date(Date.now() - 5 * 60000).toISOString(),
    cashierName: 'Priya',
  },
];
