import { Category, MenuItem, InventoryItem, Order, User } from './types';
import { APP_CONFIG } from './config';

export const initialCategories: Category[] = [
  {
    "id": "cat-1",
    "name": "slow mornings",
    "description": "buns, bowls, omelettes & breakfast comfort",
    "order": 1
  },
  {
    "id": "cat-2",
    "name": "big sandwiches",
    "description": "layered toasties, deckers & grilled panini",
    "order": 2
  },
  {
    "id": "cat-3",
    "name": "bowls & comfort",
    "description": "homestyle dal, rajma, khichdi & warm grain bowls",
    "order": 3
  },
  {
    "id": "cat-4",
    "name": "something green",
    "description": "fresh wholesome salads & warm roasted greens",
    "order": 4
  },
  {
    "id": "cat-5",
    "name": "pasta & pizza",
    "description": "artisan pasta & sourdough pizzas",
    "order": 5
  },
  {
    "id": "cat-6",
    "name": "got the munchies",
    "description": "vada pav, crispy bites & sharing boards",
    "order": 6
  },
  {
    "id": "cat-7",
    "name": "there's always room",
    "description": "warm brownies, affogato & sweet conclusions",
    "order": 7
  },
  {
    "id": "cat-8",
    "name": "coffee, obviously",
    "description": "espresso, pour overs, flat whites & cold brews",
    "order": 8
  },
  {
    "id": "cat-9",
    "name": "cold & easy",
    "description": "fresh lime soda, iced tea & seasonal coolers",
    "order": 9
  },
  {
    "id": "cat-10",
    "name": "shakes",
    "description": "thick wholesome shakes & fruit blends",
    "order": 10
  },
  {
    "id": "cat-11",
    "name": "smol experiments",
    "description": "buransh fizz, jaggery lattes & signature lab",
    "order": 11
  },
  {
    "id": "cat-12",
    "name": "chai, chaas & other good decisions",
    "description": "kadak chai, herbal infusions & spiced chaas",
    "order": 12
  },
  {
    "id": "cat-13",
    "name": "chai ke saathi",
    "description": "classic chai paired with comfort bites",
    "order": 13
  }
];

export const initialMenuItems: MenuItem[] = [
  {
    "id": "item-1",
    "name": "Bun Makkhan, Kanpur Se",
    "categoryId": "cat-1",
    "price": 79,
    "description": "Warm toasted bun with generous salted butter.",
    "available": true,
    "isVeg": true,
    "isEgg": false,
    "isVegan": false,
    "isSpecial": false,
    "image": "/items/bun_makkhan.jpg",
    "subcategory": "Breakfast",
    "coreIngredients": "Bun, salted butter",
    "sharedPrePrep": "Portion butter; slice buns",
    "primaryEquipment": "OTG / panini grill",
    "servingWare": "7\u20138 in side plate",
    "targetPrice": 79,
    "ceilingPrice": 89,
    "availability": "All Day",
    "bestPairing": "Smol Chai / Adrak Chai",
    "dietary": "Vegetarian",
    "proteinFocus": "Low",
    "spice": "Mild",
    "menuStatus": "Core",
    "notes": "Keep deliberately simple; signature nostalgia item."
  },
  {
    "id": "item-2",
    "name": "Oats, Fruit & Yoghurt Bowl",
    "categoryId": "cat-1",
    "price": 179,
    "description": "Rolled oats, yoghurt, seasonal fruit, banana, seeds/granola and honey or jaggery.",
    "available": true,
    "isVeg": true,
    "isEgg": false,
    "isVegan": false,
    "isSpecial": false,
    "image": "/items/oats_fruit_bowl.jpg",
    "subcategory": "Breakfast",
    "coreIngredients": "Rolled oats, yoghurt, banana, seasonal fruit, seeds/granola, honey/jaggery",
    "sharedPrePrep": "Portion oats; cut fruit; granola batch",
    "primaryEquipment": "No-cook / microwave optional",
    "servingWare": "9 in universal deep bowl",
    "targetPrice": 179,
    "ceilingPrice": 189,
    "availability": "All Day",
    "bestPairing": "Americano / Iced Coffee",
    "dietary": "Vegetarian; plant-milk adaptable",
    "proteinFocus": "Medium",
    "spice": "None",
    "menuStatus": "Core",
    "notes": "Use seasonal fruit only; avoid large fruit inventory."
  },
  {
    "id": "item-3",
    "name": "Masala Omelette Breakfast",
    "categoryId": "cat-1",
    "price": 159,
    "description": "Masala omelette with toast, house pickle and crispy herbed potatoes.",
    "available": true,
    "isVeg": false,
    "isEgg": true,
    "isVegan": false,
    "isSpecial": false,
    "image": "/items/masala_omelette.jpg",
    "subcategory": "Breakfast",
    "coreIngredients": "Eggs, onion, tomato, chilli, coriander, bread, potatoes, pickle",
    "sharedPrePrep": "Chopped omelette mix; herbed potato batch; house pickle",
    "primaryEquipment": "Gas / induction + air fryer",
    "servingWare": "10 in main plate",
    "targetPrice": 159,
    "ceilingPrice": 179,
    "availability": "All Day",
    "bestPairing": "Chai / Coffee",
    "dietary": "Egg",
    "proteinFocus": "High",
    "spice": "Medium",
    "menuStatus": "Core",
    "notes": "Egg legality/operational permission to be confirmed for exact property."
  },
  {
    "id": "item-4",
    "name": "Creamy Cheese Mushroom Omelette",
    "categoryId": "cat-1",
    "price": 189,
    "description": "Egg omelette with creamy garlic-herb mushrooms and cheese; toast and slaw.",
    "available": true,
    "isVeg": false,
    "isEgg": true,
    "isVegan": false,
    "isSpecial": false,
    "image": "/items/masala_omelette.jpg",
    "subcategory": "Breakfast",
    "coreIngredients": "Eggs, mushroom, garlic, herbs, cheese, bread, slaw",
    "sharedPrePrep": "Creamy mushroom base; slaw",
    "primaryEquipment": "Gas / induction",
    "servingWare": "10 in main plate",
    "targetPrice": 189,
    "ceilingPrice": 209,
    "availability": "All Day",
    "bestPairing": "Cappuccino / Americano",
    "dietary": "Egg; Vegetarian otherwise",
    "proteinFocus": "High",
    "spice": "Mild",
    "menuStatus": "Core",
    "notes": null
  },
  {
    "id": "item-5",
    "name": "Egg Bhurji Pav",
    "categoryId": "cat-1",
    "price": 149,
    "description": "Masala egg bhurji with warm buttered pav and house pickle.",
    "available": true,
    "isVeg": false,
    "isEgg": true,
    "isVegan": false,
    "isSpecial": false,
    "image": "/items/bhurji_pav.jpg",
    "subcategory": "Breakfast",
    "coreIngredients": "Eggs, onion, tomato, chilli, coriander, pav, butter, pickle",
    "sharedPrePrep": "Bhurji masala base; sliced pav",
    "primaryEquipment": "Gas + grill/OTG",
    "servingWare": "10 in main plate",
    "targetPrice": 149,
    "ceilingPrice": 169,
    "availability": "All Day",
    "bestPairing": "Smol Chai",
    "dietary": "Egg",
    "proteinFocus": "High",
    "spice": "Medium",
    "menuStatus": "Core",
    "notes": null
  },
  {
    "id": "item-6",
    "name": "Paneer Bhurji Pav",
    "categoryId": "cat-1",
    "price": 159,
    "description": "Masala paneer bhurji with warm buttered pav and house pickle.",
    "available": true,
    "isVeg": true,
    "isEgg": false,
    "isVegan": false,
    "isSpecial": false,
    "image": "/items/bhurji_pav.jpg",
    "subcategory": "Breakfast",
    "coreIngredients": "Paneer, onion, tomato, chilli, coriander, pav, butter, pickle",
    "sharedPrePrep": "Bhurji masala base; crumble paneer; sliced pav",
    "primaryEquipment": "Gas + grill/OTG",
    "servingWare": "10 in main plate",
    "targetPrice": 159,
    "ceilingPrice": 179,
    "availability": "All Day",
    "bestPairing": "Smol Chai",
    "dietary": "Vegetarian",
    "proteinFocus": "High",
    "spice": "Medium",
    "menuStatus": "Core",
    "notes": null
  },
  {
    "id": "item-7",
    "name": "The Smol Triple Decker",
    "categoryId": "cat-2",
    "price": 199,
    "description": "Three-layer toasted sandwich with masala potato, green chutney, vegetables, cheese and creamy paneer spread.",
    "available": true,
    "isVeg": true,
    "isEgg": false,
    "isVegan": false,
    "isSpecial": false,
    "image": "/items/triple_decker.jpg",
    "subcategory": "Sandwich",
    "coreIngredients": "Bread, masala potato, green chutney, tomato, cucumber, cheese, paneer spread",
    "sharedPrePrep": "Masala potato; chutney; paneer spread; sliced vegetables",
    "primaryEquipment": "Panini grill / OTG",
    "servingWare": "10 in main plate",
    "targetPrice": 199,
    "ceilingPrice": 209,
    "availability": "All Day",
    "bestPairing": "Chai / Lemonade",
    "dietary": "Vegetarian",
    "proteinFocus": "Medium",
    "spice": "Medium",
    "menuStatus": "Core",
    "notes": "Sagar Gaire-inspired format, not copied recipe."
  },
  {
    "id": "item-8",
    "name": "Creamy Cheese Mushroom Decker",
    "categoryId": "cat-2",
    "price": 219,
    "description": "Three-layer sandwich with creamy garlic-herb mushrooms, caramelised onion and melted cheese.",
    "available": true,
    "isVeg": true,
    "isEgg": false,
    "isVegan": false,
    "isSpecial": false,
    "image": "/item_mushroom.jpg",
    "subcategory": "Sandwich",
    "coreIngredients": "Bread, mushroom, garlic, herbs, onion, cheese",
    "sharedPrePrep": "Creamy mushroom base; caramelised onion",
    "primaryEquipment": "Panini grill / OTG",
    "servingWare": "10 in main plate",
    "targetPrice": 219,
    "ceilingPrice": 229,
    "availability": "All Day",
    "bestPairing": "Cappuccino / Iced Tea",
    "dietary": "Vegetarian",
    "proteinFocus": "Medium",
    "spice": "Mild",
    "menuStatus": "Core",
    "notes": null
  },
  {
    "id": "item-9",
    "name": "Chickpea Paneer Protein Decker",
    "categoryId": "cat-2",
    "price": 219,
    "description": "Smashed chickpeas, paneer, cucumber, tomato, herbs and yoghurt-chilli spread.",
    "available": true,
    "isVeg": true,
    "isEgg": false,
    "isVegan": false,
    "isSpecial": false,
    "image": "/items/triple_decker.jpg",
    "subcategory": "Sandwich",
    "coreIngredients": "Bread, chickpeas, paneer, cucumber, tomato, yoghurt, herbs, chilli",
    "sharedPrePrep": "Cooked chickpeas; chickpea mash; paneer portion; yoghurt spread",
    "primaryEquipment": "Panini grill / OTG",
    "servingWare": "10 in main plate",
    "targetPrice": 219,
    "ceilingPrice": 229,
    "availability": "All Day",
    "bestPairing": "Lemonade / Americano",
    "dietary": "Vegetarian",
    "proteinFocus": "High",
    "spice": "Mild-Medium",
    "menuStatus": "Core",
    "notes": null
  },
  {
    "id": "item-10",
    "name": "Bombay Toastie",
    "categoryId": "cat-2",
    "price": 169,
    "description": "Masala potato, vegetables, green chutney and cheese.",
    "available": true,
    "isVeg": true,
    "isEgg": false,
    "isVegan": false,
    "isSpecial": false,
    "image": "/item_panini.jpg",
    "subcategory": "Sandwich",
    "coreIngredients": "Bread, potato, tomato, onion, cucumber, green chutney, cheese",
    "sharedPrePrep": "Masala potato; chutney; sliced vegetables",
    "primaryEquipment": "Panini grill / OTG",
    "servingWare": "10 in main plate",
    "targetPrice": 169,
    "ceilingPrice": 179,
    "availability": "All Day",
    "bestPairing": "Smol Chai",
    "dietary": "Vegetarian",
    "proteinFocus": "Low-Medium",
    "spice": "Medium",
    "menuStatus": "Core",
    "notes": null
  },
  {
    "id": "item-11",
    "name": "Ghar Wali Dal Khichdi",
    "categoryId": "cat-3",
    "price": 149,
    "description": "Moong dal and rice khichdi with ghee tadka; yoghurt, pickle and papad.",
    "available": true,
    "isVeg": true,
    "isEgg": false,
    "isVegan": false,
    "isSpecial": false,
    "image": "/items/dal_khichdi.jpg",
    "subcategory": "Comfort Bowl",
    "coreIngredients": "Moong dal, rice, ghee, cumin, garlic, yoghurt, pickle, papad",
    "sharedPrePrep": "Cooked khichdi base; tadka mise en place",
    "primaryEquipment": "Pressure cooker / gas",
    "servingWare": "9 in universal deep bowl",
    "targetPrice": 149,
    "ceilingPrice": 159,
    "availability": "All Day",
    "bestPairing": "Chaas / Chai",
    "dietary": "Vegetarian",
    "proteinFocus": "Medium",
    "spice": "Mild",
    "menuStatus": "Core",
    "notes": null
  },
  {
    "id": "item-12",
    "name": "Dal Chawal Bowl",
    "categoryId": "cat-3",
    "price": 149,
    "description": "Homestyle dal, steamed rice, ghee tadka, pickled onion and papad.",
    "available": true,
    "isVeg": true,
    "isEgg": false,
    "isVegan": false,
    "isSpecial": false,
    "image": "/items/dal_khichdi.jpg",
    "subcategory": "Comfort Bowl",
    "coreIngredients": "Dal, rice, ghee, garlic, cumin, pickled onion, papad",
    "sharedPrePrep": "Cooked dal; steamed rice; tadka; pickled onion",
    "primaryEquipment": "Gas / induction",
    "servingWare": "9 in universal deep bowl",
    "targetPrice": 149,
    "ceilingPrice": 159,
    "availability": "All Day",
    "bestPairing": "Masala Chaas",
    "dietary": "Vegetarian",
    "proteinFocus": "Medium-High",
    "spice": "Mild-Medium",
    "menuStatus": "Core",
    "notes": null
  },
  {
    "id": "item-13",
    "name": "Rajma Chawal Bowl",
    "categoryId": "cat-3",
    "price": 159,
    "description": "Slow-cooked rajma, rice, pickled onion, yoghurt and papad crunch.",
    "available": true,
    "isVeg": true,
    "isEgg": false,
    "isVegan": false,
    "isSpecial": false,
    "image": "/items/rajma_chawal.jpg",
    "subcategory": "Comfort Bowl",
    "coreIngredients": "Rajma, rice, tomato-onion masala, yoghurt, pickled onion, papad",
    "sharedPrePrep": "Soaked/cooked rajma; base gravy; steamed rice",
    "primaryEquipment": "Gas / pressure cooker",
    "servingWare": "9 in universal deep bowl",
    "targetPrice": 159,
    "ceilingPrice": 169,
    "availability": "All Day",
    "bestPairing": "Chaas / Lime Soda",
    "dietary": "Vegetarian",
    "proteinFocus": "High",
    "spice": "Medium",
    "menuStatus": "Core",
    "notes": null
  },
  {
    "id": "item-14",
    "name": "Chana Crunch Bowl",
    "categoryId": "cat-3",
    "price": 169,
    "description": "Spiced chickpeas, rice, cucumber, tomato, slaw, mint yoghurt and crispy chana.",
    "available": true,
    "isVeg": true,
    "isEgg": false,
    "isVegan": false,
    "isSpecial": false,
    "image": "/items/paneer_rice_bowl.jpg",
    "subcategory": "Protein Bowl",
    "coreIngredients": "Chickpeas, rice, cucumber, tomato, cabbage/carrot slaw, yoghurt, mint, spices",
    "sharedPrePrep": "Cooked chickpeas; crispy chana batch; slaw; mint yoghurt; rice",
    "primaryEquipment": "Gas + air fryer",
    "servingWare": "9 in universal deep bowl",
    "targetPrice": 169,
    "ceilingPrice": 179,
    "availability": "All Day",
    "bestPairing": "Lemonade / Chaas",
    "dietary": "Vegetarian",
    "proteinFocus": "High",
    "spice": "Medium",
    "menuStatus": "Core",
    "notes": null
  },
  {
    "id": "item-15",
    "name": "Smoky Paneer Rice Bowl",
    "categoryId": "cat-3",
    "price": 199,
    "description": "Smoky paneer, rice, roasted vegetables, cucumber, pickled onion and mint yoghurt.",
    "available": true,
    "isVeg": true,
    "isEgg": false,
    "isVegan": false,
    "isSpecial": false,
    "image": "/items/paneer_rice_bowl.jpg",
    "subcategory": "Protein Bowl",
    "coreIngredients": "Paneer, rice, seasonal vegetables, cucumber, pickled onion, yoghurt, mint",
    "sharedPrePrep": "Paneer marinade; roasted veg; mint yoghurt; pickled onion; rice",
    "primaryEquipment": "Gas / OTG",
    "servingWare": "9 in universal deep bowl",
    "targetPrice": 199,
    "ceilingPrice": 209,
    "availability": "All Day",
    "bestPairing": "Iced Tea / Lime Soda",
    "dietary": "Vegetarian",
    "proteinFocus": "High",
    "spice": "Medium",
    "menuStatus": "Core",
    "notes": null
  },
  {
    "id": "item-16",
    "name": "Creamy Mushroom & Herb Rice",
    "categoryId": "cat-3",
    "price": 199,
    "description": "Creamy garlic-herb mushrooms over herbed rice with roast vegetables and a fresh crunchy side.",
    "available": true,
    "isVeg": true,
    "isEgg": false,
    "isVegan": false,
    "isSpecial": false,
    "image": "/items/paneer_rice_bowl.jpg",
    "subcategory": "Comfort Bowl",
    "coreIngredients": "Mushrooms, garlic, cream, herbs, rice, seasonal vegetables, slaw/cucumber",
    "sharedPrePrep": "Creamy mushroom base; herbed rice; roasted vegetables",
    "primaryEquipment": "Gas / induction",
    "servingWare": "9 in universal deep bowl",
    "targetPrice": 199,
    "ceilingPrice": 209,
    "availability": "All Day",
    "bestPairing": "Americano / Iced Tea",
    "dietary": "Vegetarian",
    "proteinFocus": "Medium",
    "spice": "Mild",
    "menuStatus": "Core",
    "notes": null
  },
  {
    "id": "item-17",
    "name": "Crunchy Chana Salad",
    "categoryId": "cat-4",
    "price": 169,
    "description": "Chickpeas, cucumber, tomato, carrot, cabbage, herbs, seeds, pickled onion and lemon dressing.",
    "available": true,
    "isVeg": true,
    "isEgg": false,
    "isVegan": true,
    "isSpecial": false,
    "image": "/home_salad_clean.png",
    "subcategory": "Salad",
    "coreIngredients": "Chickpeas, cucumber, tomato, carrot, cabbage, herbs, seeds, pickled onion, lemon",
    "sharedPrePrep": "Cooked chickpeas; slaw prep; pickled onion; dressing",
    "primaryEquipment": "No-cook",
    "servingWare": "9 in universal deep bowl",
    "targetPrice": 169,
    "ceilingPrice": 179,
    "availability": "All Day",
    "bestPairing": "Lemonade / Juice",
    "dietary": "Vegan adaptable",
    "proteinFocus": "High",
    "spice": "Mild",
    "menuStatus": "Core",
    "notes": null
  },
  {
    "id": "item-18",
    "name": "Warm Mushroom & Roast Veg Salad",
    "categoryId": "cat-4",
    "price": 189,
    "description": "Warm creamy/herbed mushrooms, roasted seasonal vegetables, crispy chickpeas, seeds and mustard-lemon dressing.",
    "available": true,
    "isVeg": true,
    "isEgg": false,
    "isVegan": false,
    "isSpecial": false,
    "image": "/home_salad_clean.png",
    "subcategory": "Salad",
    "coreIngredients": "Mushroom, seasonal vegetables, chickpeas, seeds, mustard, lemon, herbs",
    "sharedPrePrep": "Creamy/herbed mushroom; roasted veg; crispy chickpeas; dressing",
    "primaryEquipment": "OTG + gas",
    "servingWare": "9 in universal deep bowl",
    "targetPrice": 189,
    "ceilingPrice": 199,
    "availability": "All Day",
    "bestPairing": "Americano / Lime Soda",
    "dietary": "Vegetarian",
    "proteinFocus": "Medium",
    "spice": "Mild",
    "menuStatus": "Core",
    "notes": null
  },
  {
    "id": "item-19",
    "name": "Smol Pink Pasta",
    "categoryId": "cat-5",
    "price": 189,
    "description": "Tomato, garlic, light cream and cheese.",
    "available": true,
    "isVeg": true,
    "isEgg": false,
    "isVegan": false,
    "isSpecial": false,
    "image": "/items/pink_pasta.jpg",
    "subcategory": "Pasta",
    "coreIngredients": "Pasta, tomato sauce, garlic, cream, cheese, herbs",
    "sharedPrePrep": "Tomato sauce base; par-cooked pasta optional",
    "primaryEquipment": "Gas / induction",
    "servingWare": "9 in universal deep bowl",
    "targetPrice": 189,
    "ceilingPrice": 199,
    "availability": "All Day",
    "bestPairing": "Iced Tea / Lime Soda",
    "dietary": "Vegetarian",
    "proteinFocus": "Low-Medium",
    "spice": "Mild",
    "menuStatus": "Core",
    "notes": null
  },
  {
    "id": "item-20",
    "name": "Garlic Chilli Aglio Olio",
    "categoryId": "cat-5",
    "price": 179,
    "description": "Garlic, chilli, olive oil and herbs.",
    "available": true,
    "isVeg": true,
    "isEgg": false,
    "isVegan": true,
    "isSpecial": false,
    "image": "/items/pink_pasta.jpg",
    "subcategory": "Pasta",
    "coreIngredients": "Pasta, garlic, chilli, olive oil, herbs, optional cheese",
    "sharedPrePrep": "Garlic/chilli mise en place; par-cooked pasta optional",
    "primaryEquipment": "Gas / induction",
    "servingWare": "9 in universal deep bowl",
    "targetPrice": 179,
    "ceilingPrice": 189,
    "availability": "All Day",
    "bestPairing": "Americano / Lemonade",
    "dietary": "Vegan adaptable",
    "proteinFocus": "Low",
    "spice": "Medium",
    "menuStatus": "Core",
    "notes": null
  },
  {
    "id": "item-21",
    "name": "Classic Margherita",
    "categoryId": "cat-5",
    "price": 199,
    "description": "Tomato, mozzarella and basil.",
    "available": true,
    "isVeg": true,
    "isEgg": false,
    "isVegan": false,
    "isSpecial": false,
    "image": "/items/margherita_pizza.jpg",
    "subcategory": "Pizza",
    "coreIngredients": "Pizza dough, tomato sauce, mozzarella, basil",
    "sharedPrePrep": "Pizza dough; tomato sauce; grated cheese",
    "primaryEquipment": "OTG",
    "servingWare": "10 in main plate",
    "targetPrice": 199,
    "ceilingPrice": 209,
    "availability": "All Day",
    "bestPairing": "Cold Coffee / Lime Soda",
    "dietary": "Vegetarian",
    "proteinFocus": "Medium",
    "spice": "Mild",
    "menuStatus": "Core",
    "notes": null
  },
  {
    "id": "item-22",
    "name": "Paneer Tikka & Pickled Onion Pizza",
    "categoryId": "cat-5",
    "price": 219,
    "description": "Paneer, tomato sauce, mozzarella, pickled onion and coriander.",
    "available": true,
    "isVeg": true,
    "isEgg": false,
    "isVegan": false,
    "isSpecial": false,
    "image": "/items/margherita_pizza.jpg",
    "subcategory": "Pizza",
    "coreIngredients": "Pizza dough, paneer, tomato sauce, cheese, pickled onion, coriander",
    "sharedPrePrep": "Dough; tomato sauce; paneer marinade; pickled onion",
    "primaryEquipment": "OTG",
    "servingWare": "10 in main plate",
    "targetPrice": 219,
    "ceilingPrice": 229,
    "availability": "All Day",
    "bestPairing": "Lemonade / Iced Tea",
    "dietary": "Vegetarian",
    "proteinFocus": "High",
    "spice": "Medium",
    "menuStatus": "Core",
    "notes": null
  },
  {
    "id": "item-23",
    "name": "Creamy Mushroom & Herb Pizza",
    "categoryId": "cat-5",
    "price": 219,
    "description": "Creamy garlic mushrooms, mozzarella, herbs and chilli oil.",
    "available": true,
    "isVeg": true,
    "isEgg": false,
    "isVegan": false,
    "isSpecial": false,
    "image": "/items/margherita_pizza.jpg",
    "subcategory": "Pizza",
    "coreIngredients": "Pizza dough, creamy mushrooms, mozzarella, herbs, chilli oil",
    "sharedPrePrep": "Dough; creamy mushroom base; chilli oil",
    "primaryEquipment": "OTG",
    "servingWare": "10 in main plate",
    "targetPrice": 219,
    "ceilingPrice": 229,
    "availability": "All Day",
    "bestPairing": "Americano / Iced Tea",
    "dietary": "Vegetarian",
    "proteinFocus": "Medium",
    "spice": "Mild-Medium",
    "menuStatus": "Core",
    "notes": null
  },
  {
    "id": "item-24",
    "name": "Pizza Lab \u2013 Rotating",
    "categoryId": "cat-5",
    "price": 229,
    "description": "One experimental pizza rotates every few weeks: Bhutta Chilli Cheese / Aloo Achaar / Green Chutney Paneer / other test.",
    "available": true,
    "isVeg": true,
    "isEgg": false,
    "isVegan": false,
    "isSpecial": true,
    "image": "/items/margherita_pizza.jpg",
    "subcategory": "Pizza Lab",
    "coreIngredients": "Uses existing dough + rotating toppings",
    "sharedPrePrep": "Same dough/tomato/cheese system; one rotating topping prep",
    "primaryEquipment": "OTG",
    "servingWare": "10 in main plate",
    "targetPrice": 229,
    "ceilingPrice": 249,
    "availability": "All Day when active",
    "bestPairing": "Seasonal drink / Iced Tea",
    "dietary": "Varies",
    "proteinFocus": "Varies",
    "spice": "Varies",
    "menuStatus": "Seasonal",
    "notes": "All-day while active. Keep one experiment only."
  },
  {
    "id": "item-25",
    "name": "Vada Pav",
    "categoryId": "cat-6",
    "price": 89,
    "description": "Potato vada, garlic chutney, green chutney and chilli.",
    "available": true,
    "isVeg": true,
    "isEgg": false,
    "isVegan": false,
    "isSpecial": false,
    "image": "/items/vada_pav.jpg",
    "subcategory": "Snack",
    "coreIngredients": "Pav, potato vada, garlic chutney, green chutney, chilli",
    "sharedPrePrep": "Potato filling; vada batter; chutneys",
    "primaryEquipment": "Gas / air fryer or fry setup",
    "servingWare": "7\u20138 in side plate",
    "targetPrice": 89,
    "ceilingPrice": 99,
    "availability": "All Day",
    "bestPairing": "Smol Chai",
    "dietary": "Vegetarian",
    "proteinFocus": "Low-Medium",
    "spice": "Medium",
    "menuStatus": "Core",
    "notes": null
  },
  {
    "id": "item-26",
    "name": "Timur Crispy Potatoes",
    "categoryId": "cat-6",
    "price": 139,
    "description": "Air-crisped potatoes, garlic, timur seasoning and herb yoghurt.",
    "available": true,
    "isVeg": true,
    "isEgg": false,
    "isVegan": false,
    "isSpecial": false,
    "image": "/items/timur_potatoes.jpg",
    "subcategory": "Snack",
    "coreIngredients": "Potatoes, garlic, timur, herbs, yoghurt",
    "sharedPrePrep": "Par-cooked potatoes; seasoning; herb yoghurt",
    "primaryEquipment": "Air fryer",
    "servingWare": "Small serving bowl",
    "targetPrice": 139,
    "ceilingPrice": 149,
    "availability": "All Day",
    "bestPairing": "Iced Tea / Chai",
    "dietary": "Vegetarian",
    "proteinFocus": "Low",
    "spice": "Medium",
    "menuStatus": "Core",
    "notes": null
  },
  {
    "id": "item-27",
    "name": "Crispy Corn",
    "categoryId": "cat-6",
    "price": 139,
    "description": "Corn, chilli, lime and spring onion.",
    "available": true,
    "isVeg": true,
    "isEgg": false,
    "isVegan": false,
    "isSpecial": false,
    "image": "/items/timur_potatoes.jpg",
    "subcategory": "Snack",
    "coreIngredients": "Corn, chilli, lime, spring onion, seasoning",
    "sharedPrePrep": "Portion corn; chop spring onion",
    "primaryEquipment": "Wok / air fryer",
    "servingWare": "Small serving bowl",
    "targetPrice": 139,
    "ceilingPrice": 149,
    "availability": "All Day",
    "bestPairing": "Lime Soda / Cold Coffee",
    "dietary": "Vegetarian",
    "proteinFocus": "Low",
    "spice": "Medium",
    "menuStatus": "Core",
    "notes": null
  },
  {
    "id": "item-28",
    "name": "Chilli Cheese Toast Fingers",
    "categoryId": "cat-6",
    "price": 129,
    "description": "Cheese, chilli and herbs on crisp toast.",
    "available": true,
    "isVeg": true,
    "isEgg": false,
    "isVegan": false,
    "isSpecial": false,
    "image": "/item_panini.jpg",
    "subcategory": "Snack",
    "coreIngredients": "Bread, cheese, chilli, herbs, butter",
    "sharedPrePrep": "Cheese mix; cut toast fingers",
    "primaryEquipment": "OTG / grill",
    "servingWare": "7\u20138 in side plate",
    "targetPrice": 129,
    "ceilingPrice": 139,
    "availability": "All Day",
    "bestPairing": "Smol Chai / Coffee",
    "dietary": "Vegetarian",
    "proteinFocus": "Medium",
    "spice": "Medium",
    "menuStatus": "Core",
    "notes": null
  },
  {
    "id": "item-29",
    "name": "Loaded Papad Nachos",
    "categoryId": "cat-6",
    "price": 199,
    "description": "Papad crisps, chickpeas or rajma, cheese, yoghurt, tomato, chutneys and pickled onions.",
    "available": true,
    "isVeg": true,
    "isEgg": false,
    "isVegan": false,
    "isSpecial": false,
    "image": "/items/timur_potatoes.jpg",
    "subcategory": "Sharing",
    "coreIngredients": "Papad, chickpeas/rajma, cheese, yoghurt, tomato, chutneys, pickled onions",
    "sharedPrePrep": "Roasted papad; cooked legumes; chutneys; pickled onions",
    "primaryEquipment": "OTG + assembly",
    "servingWare": "Large sharing platter",
    "targetPrice": 199,
    "ceilingPrice": 219,
    "availability": "All Day",
    "bestPairing": "Lime Soda / Seasonal Drink",
    "dietary": "Vegetarian",
    "proteinFocus": "Medium-High",
    "spice": "Medium",
    "menuStatus": "Core",
    "notes": null
  },
  {
    "id": "item-30",
    "name": "Conversation Board",
    "categoryId": "cat-6",
    "price": 329,
    "description": "A changing sharing board with smashed chickpea dip, crispy chana, toast, potatoes, pickle, vegetables and seasonal dips.",
    "available": true,
    "isVeg": true,
    "isEgg": false,
    "isVegan": true,
    "isSpecial": false,
    "image": "/conversation-board.png",
    "subcategory": "Sharing",
    "coreIngredients": "Chickpeas, bread, potatoes, vegetables, pickle, yoghurt/tahini dips",
    "sharedPrePrep": "Chickpea dip; crispy chana; toast; potatoes; dips; pickles",
    "primaryEquipment": "Mixed / assembly",
    "servingWare": "Large sharing platter",
    "targetPrice": 329,
    "ceilingPrice": 349,
    "availability": "All Day",
    "bestPairing": "Coffee / Seasonal Drink",
    "dietary": "Vegetarian; vegan adaptable",
    "proteinFocus": "Medium-High",
    "spice": "Mild-Medium",
    "menuStatus": "Core",
    "notes": "Keep components flexible to absorb prep surplus and seasonal produce."
  },
  {
    "id": "item-31",
    "name": "Affogato",
    "categoryId": "cat-7",
    "price": 129,
    "description": "Vanilla ice cream with a shot of espresso.",
    "available": true,
    "isVeg": true,
    "isEgg": false,
    "isVegan": false,
    "isSpecial": false,
    "image": "/item-espresso.png",
    "subcategory": "Dessert",
    "coreIngredients": "Vanilla ice cream, espresso",
    "sharedPrePrep": "Portion ice cream",
    "primaryEquipment": "Espresso machine",
    "servingWare": "Small dessert bowl / cup",
    "targetPrice": 129,
    "ceilingPrice": 139,
    "availability": "All Day",
    "bestPairing": "\u2014",
    "dietary": "Vegetarian",
    "proteinFocus": "Low",
    "spice": "None",
    "menuStatus": "Core",
    "notes": null
  },
  {
    "id": "item-32",
    "name": "Warm Chocolate Brownie",
    "categoryId": "cat-7",
    "price": 149,
    "description": "Warm brownie, vanilla ice cream and sea salt.",
    "available": true,
    "isVeg": true,
    "isEgg": false,
    "isVegan": false,
    "isSpecial": false,
    "image": "/item_chocolatecake.jpg",
    "subcategory": "Dessert",
    "coreIngredients": "Brownie, vanilla ice cream, sea salt",
    "sharedPrePrep": "Bake brownie batch; portion",
    "primaryEquipment": "OTG + microwave",
    "servingWare": "7\u20138 in side plate",
    "targetPrice": 149,
    "ceilingPrice": 169,
    "availability": "All Day",
    "bestPairing": "Cappuccino / Americano",
    "dietary": "Vegetarian",
    "proteinFocus": "Low",
    "spice": "None",
    "menuStatus": "Core",
    "notes": null
  },
  {
    "id": "item-33",
    "name": "Espresso",
    "categoryId": "cat-8",
    "price": 79,
    "description": "Single espresso.",
    "available": true,
    "isVeg": true,
    "isEgg": false,
    "isVegan": true,
    "isSpecial": false,
    "image": "/item-espresso-arch.png",
    "subcategory": "Coffee",
    "coreIngredients": "Coffee beans, water",
    "sharedPrePrep": "Dial-in grinder",
    "primaryEquipment": "Espresso machine",
    "servingWare": "Espresso cup",
    "targetPrice": 79,
    "ceilingPrice": 89,
    "availability": "All Day",
    "bestPairing": "Brownie / Affogato",
    "dietary": "Vegan",
    "proteinFocus": "Low",
    "spice": "None",
    "menuStatus": "Core",
    "notes": null
  },
  {
    "id": "item-34",
    "name": "Americano",
    "categoryId": "cat-8",
    "price": 99,
    "description": "Espresso with hot water.",
    "available": true,
    "isVeg": true,
    "isEgg": false,
    "isVegan": true,
    "isSpecial": false,
    "image": "/item-pourover.png",
    "subcategory": "Coffee",
    "coreIngredients": "Coffee beans, water",
    "sharedPrePrep": "Dial-in grinder",
    "primaryEquipment": "Espresso machine",
    "servingWare": "Coffee cup",
    "targetPrice": 99,
    "ceilingPrice": 109,
    "availability": "All Day",
    "bestPairing": "Oats Bowl / Aglio Olio",
    "dietary": "Vegan",
    "proteinFocus": "Low",
    "spice": "None",
    "menuStatus": "Core",
    "notes": null
  },
  {
    "id": "item-35",
    "name": "Cappuccino",
    "categoryId": "cat-8",
    "price": 119,
    "description": "Espresso with steamed milk and foam.",
    "available": true,
    "isVeg": true,
    "isEgg": false,
    "isVegan": false,
    "isSpecial": false,
    "image": "/item-flatwhite-arch.png",
    "subcategory": "Coffee",
    "coreIngredients": "Coffee beans, milk",
    "sharedPrePrep": "Dial-in grinder; chilled milk",
    "primaryEquipment": "Espresso machine",
    "servingWare": "Cappuccino cup",
    "targetPrice": 119,
    "ceilingPrice": 129,
    "availability": "All Day",
    "bestPairing": "Mushroom Omelette / Brownie",
    "dietary": "Vegetarian",
    "proteinFocus": "Medium",
    "spice": "None",
    "menuStatus": "Core",
    "notes": null
  },
  {
    "id": "item-36",
    "name": "Caf\u00e9 Latte",
    "categoryId": "cat-8",
    "price": 129,
    "description": "Espresso with steamed milk.",
    "available": true,
    "isVeg": true,
    "isEgg": false,
    "isVegan": false,
    "isSpecial": false,
    "image": "/item-flatwhite-arch.png",
    "subcategory": "Coffee",
    "coreIngredients": "Coffee beans, milk",
    "sharedPrePrep": "Dial-in grinder; chilled milk",
    "primaryEquipment": "Espresso machine",
    "servingWare": "Latte cup",
    "targetPrice": 129,
    "ceilingPrice": 139,
    "availability": "All Day",
    "bestPairing": "Breakfast / Sandwiches",
    "dietary": "Vegetarian",
    "proteinFocus": "Medium",
    "spice": "None",
    "menuStatus": "Core",
    "notes": null
  },
  {
    "id": "item-37",
    "name": "Classic Cold Coffee",
    "categoryId": "cat-8",
    "price": 139,
    "description": "Coffee, milk, ice and restrained sweetness.",
    "available": true,
    "isVeg": true,
    "isEgg": false,
    "isVegan": false,
    "isSpecial": false,
    "image": "/mood-coffee-card.png",
    "subcategory": "Coffee",
    "coreIngredients": "Coffee, milk, ice, sugar/jaggery",
    "sharedPrePrep": "Cold coffee concentrate optional",
    "primaryEquipment": "Blender",
    "servingWare": "Tall cold-coffee glass",
    "targetPrice": 139,
    "ceilingPrice": 149,
    "availability": "All Day",
    "bestPairing": "Chilli Cheese Toast / Pizza",
    "dietary": "Vegetarian",
    "proteinFocus": "Medium",
    "spice": "None",
    "menuStatus": "Core",
    "notes": null
  },
  {
    "id": "item-38",
    "name": "Fresh Lime Soda",
    "categoryId": "cat-9",
    "price": 69,
    "description": "Sweet, salted or mixed.",
    "available": true,
    "isVeg": true,
    "isEgg": false,
    "isVegan": true,
    "isSpecial": false,
    "image": "/item-guavafizz.png",
    "subcategory": "Cold Drink",
    "coreIngredients": "Lime, soda, sugar/salt, ice",
    "sharedPrePrep": "Lime juice; simple syrup optional",
    "primaryEquipment": "No-cook",
    "servingWare": "Universal cold-drink glass",
    "targetPrice": 69,
    "ceilingPrice": 79,
    "availability": "All Day",
    "bestPairing": "Vada Pav / Bowl",
    "dietary": "Vegan",
    "proteinFocus": "Low",
    "spice": "None",
    "menuStatus": "Core",
    "notes": null
  },
  {
    "id": "item-39",
    "name": "Cucumber Mint Lemonade",
    "categoryId": "cat-9",
    "price": 99,
    "description": "Cucumber, mint and citrus.",
    "available": true,
    "isVeg": true,
    "isEgg": false,
    "isVegan": true,
    "isSpecial": false,
    "image": "/item-guavafizz.png",
    "subcategory": "Cold Drink",
    "coreIngredients": "Cucumber, mint, lemon/lime, sugar, water, ice",
    "sharedPrePrep": "Cucumber-mint base; citrus juice",
    "primaryEquipment": "No-cook",
    "servingWare": "Universal cold-drink glass",
    "targetPrice": 99,
    "ceilingPrice": 109,
    "availability": "All Day",
    "bestPairing": "Sandwiches / Salad",
    "dietary": "Vegan",
    "proteinFocus": "Low",
    "spice": "None",
    "menuStatus": "Core",
    "notes": null
  },
  {
    "id": "item-40",
    "name": "House Iced Tea",
    "categoryId": "cat-9",
    "price": 99,
    "description": "Tea, citrus and restrained sweetness.",
    "available": true,
    "isVeg": true,
    "isEgg": false,
    "isVegan": true,
    "isSpecial": false,
    "image": "/item_rosebrew.jpg",
    "subcategory": "Cold Drink",
    "coreIngredients": "Black tea, citrus, sugar, ice",
    "sharedPrePrep": "Tea concentrate; citrus",
    "primaryEquipment": "No-cook",
    "servingWare": "Universal cold-drink glass",
    "targetPrice": 99,
    "ceilingPrice": 109,
    "availability": "All Day",
    "bestPairing": "Pizza / Pasta",
    "dietary": "Vegan",
    "proteinFocus": "Low",
    "spice": "None",
    "menuStatus": "Core",
    "notes": null
  },
  {
    "id": "item-41",
    "name": "Seasonal Fresh Juice",
    "categoryId": "cat-9",
    "price": 99,
    "description": "One or two fruits only, based on quality and season.",
    "available": true,
    "isVeg": true,
    "isEgg": false,
    "isVegan": true,
    "isSpecial": true,
    "image": "/item-guavafizz.png",
    "subcategory": "Juice",
    "coreIngredients": "Seasonal fruit, optional citrus",
    "sharedPrePrep": "Wash/cut fruit",
    "primaryEquipment": "Juicer / blender",
    "servingWare": "Universal cold-drink glass",
    "targetPrice": 99,
    "ceilingPrice": 129,
    "availability": "All Day when active",
    "bestPairing": "Breakfast / Salad",
    "dietary": "Vegan",
    "proteinFocus": "Varies",
    "spice": "None",
    "menuStatus": "Seasonal",
    "notes": "Keep only when fruit quality and cost make sense."
  },
  {
    "id": "item-42",
    "name": "Banana Peanut Butter Oats Shake",
    "categoryId": "cat-10",
    "price": 159,
    "description": "Banana, oats, peanut butter and milk; substantial enough for a light breakfast.",
    "available": true,
    "isVeg": true,
    "isEgg": false,
    "isVegan": false,
    "isSpecial": false,
    "image": "/items/oats_fruit_bowl.jpg",
    "subcategory": "Shake",
    "coreIngredients": "Banana, oats, peanut butter, milk, ice",
    "sharedPrePrep": "Portion oats and peanut butter",
    "primaryEquipment": "Blender",
    "servingWare": "Tall shake glass",
    "targetPrice": 159,
    "ceilingPrice": 169,
    "availability": "All Day",
    "bestPairing": "Breakfast",
    "dietary": "Vegetarian",
    "proteinFocus": "High",
    "spice": "None",
    "menuStatus": "Core",
    "notes": null
  },
  {
    "id": "item-43",
    "name": "Coffee Cocoa Shake",
    "categoryId": "cat-10",
    "price": 159,
    "description": "Coffee, cocoa, milk and a little ice cream.",
    "available": true,
    "isVeg": true,
    "isEgg": false,
    "isVegan": false,
    "isSpecial": false,
    "image": "/mood-coffee-card.png",
    "subcategory": "Shake",
    "coreIngredients": "Coffee, cocoa, milk, ice cream, ice",
    "sharedPrePrep": "Coffee concentrate optional",
    "primaryEquipment": "Blender",
    "servingWare": "Tall shake glass",
    "targetPrice": 159,
    "ceilingPrice": 169,
    "availability": "All Day",
    "bestPairing": "Brownie / Toast",
    "dietary": "Vegetarian",
    "proteinFocus": "Medium",
    "spice": "None",
    "menuStatus": "Core",
    "notes": null
  },
  {
    "id": "item-44",
    "name": "Seasonal Fruit & Yoghurt Shake",
    "categoryId": "cat-10",
    "price": 149,
    "description": "Seasonal fruit, yoghurt and minimal added sugar.",
    "available": true,
    "isVeg": true,
    "isEgg": false,
    "isVegan": false,
    "isSpecial": true,
    "image": "/mood-coffee-card.png",
    "subcategory": "Shake",
    "coreIngredients": "Seasonal fruit, yoghurt, milk/water, optional honey",
    "sharedPrePrep": "Prep seasonal fruit",
    "primaryEquipment": "Blender",
    "servingWare": "Tall shake glass",
    "targetPrice": 149,
    "ceilingPrice": 159,
    "availability": "All Day when active",
    "bestPairing": "Breakfast / Salad",
    "dietary": "Vegetarian",
    "proteinFocus": "Medium",
    "spice": "None",
    "menuStatus": "Seasonal",
    "notes": null
  },
  {
    "id": "item-45",
    "name": "Jaggery Sea-Salt Latte",
    "categoryId": "cat-11",
    "price": 169,
    "description": "Espresso, jaggery, milk and lightly salted foam.",
    "available": true,
    "isVeg": true,
    "isEgg": false,
    "isVegan": false,
    "isSpecial": true,
    "image": "/item-flatwhite-arch.png",
    "subcategory": "Signature Drink",
    "coreIngredients": "Coffee, milk, jaggery syrup, salt",
    "sharedPrePrep": "Jaggery syrup; salted foam mix",
    "primaryEquipment": "Espresso machine",
    "servingWare": "Latte cup / cold glass",
    "targetPrice": 169,
    "ceilingPrice": 179,
    "availability": "All Day",
    "bestPairing": "Brownie / Sandwich",
    "dietary": "Vegetarian",
    "proteinFocus": "Medium",
    "spice": "None",
    "menuStatus": "Core",
    "notes": null
  },
  {
    "id": "item-46",
    "name": "Himalayan Citrus Espresso Tonic",
    "categoryId": "cat-11",
    "price": 169,
    "description": "Espresso, house citrus cordial and tonic over ice.",
    "available": true,
    "isVeg": true,
    "isEgg": false,
    "isVegan": true,
    "isSpecial": true,
    "image": "/item_rosebrew.jpg",
    "subcategory": "Signature Drink",
    "coreIngredients": "Coffee, citrus cordial, tonic, ice",
    "sharedPrePrep": "Citrus cordial",
    "primaryEquipment": "Espresso machine",
    "servingWare": "Universal cold-drink glass",
    "targetPrice": 169,
    "ceilingPrice": 179,
    "availability": "All Day",
    "bestPairing": "Munchies / Pizza",
    "dietary": "Vegan",
    "proteinFocus": "Low",
    "spice": "None",
    "menuStatus": "Core",
    "notes": null
  },
  {
    "id": "item-47",
    "name": "Buransh Fizz",
    "categoryId": "cat-11",
    "price": 149,
    "description": "Buransh, lime and sparkling water.",
    "available": true,
    "isVeg": true,
    "isEgg": false,
    "isVegan": true,
    "isSpecial": true,
    "image": "/item-guavafizz.png",
    "subcategory": "Signature Drink",
    "coreIngredients": "Buransh cordial, lime, sparkling water, ice",
    "sharedPrePrep": "Buransh cordial",
    "primaryEquipment": "No-cook",
    "servingWare": "Universal cold-drink glass",
    "targetPrice": 149,
    "ceilingPrice": 159,
    "availability": "All Day",
    "bestPairing": "Munchies / Salad",
    "dietary": "Vegan",
    "proteinFocus": "Low",
    "spice": "None",
    "menuStatus": "Core",
    "notes": null
  },
  {
    "id": "item-48",
    "name": "Seasonal Experiment 01",
    "categoryId": "cat-11",
    "price": 149,
    "description": "Rotating seasonal drink: e.g., guava chilli fizz, peach cold brew, jamun soda or festive special.",
    "available": true,
    "isVeg": true,
    "isEgg": false,
    "isVegan": false,
    "isSpecial": true,
    "image": "/mood-food-card.png",
    "subcategory": "Seasonal Drink",
    "coreIngredients": "Rotating; prioritise existing ingredients",
    "sharedPrePrep": "One seasonal prep only",
    "primaryEquipment": "Varies",
    "servingWare": "Universal cold-drink glass",
    "targetPrice": 149,
    "ceilingPrice": 179,
    "availability": "All Day when active",
    "bestPairing": "Varies",
    "dietary": "Varies",
    "proteinFocus": "Varies",
    "spice": "Varies",
    "menuStatus": "Seasonal",
    "notes": null
  },
  {
    "id": "item-49",
    "name": "Seasonal Experiment 02",
    "categoryId": "cat-11",
    "price": 149,
    "description": "Second rotating seasonal slot; may occasionally include matcha if demand justifies it.",
    "available": true,
    "isVeg": true,
    "isEgg": false,
    "isVegan": false,
    "isSpecial": true,
    "image": "/mood-food-card.png",
    "subcategory": "Seasonal Drink",
    "coreIngredients": "Rotating; prioritise existing ingredients",
    "sharedPrePrep": "One seasonal prep only",
    "primaryEquipment": "Varies",
    "servingWare": "Universal cold-drink glass",
    "targetPrice": 149,
    "ceilingPrice": 179,
    "availability": "All Day when active",
    "bestPairing": "Varies",
    "dietary": "Varies",
    "proteinFocus": "Varies",
    "spice": "Varies",
    "menuStatus": "Seasonal",
    "notes": "Matcha is not a permanent section; only test in this slot if commercially justified."
  },
  {
    "id": "item-50",
    "name": "Smol Chai",
    "categoryId": "cat-12",
    "price": 29,
    "description": "Simple everyday chai designed as a repeat-visit traffic builder.",
    "available": true,
    "isVeg": true,
    "isEgg": false,
    "isVegan": false,
    "isSpecial": false,
    "image": "/item-kulhadchai-arch.png",
    "subcategory": "Chai",
    "coreIngredients": "Tea, milk, sugar, spices",
    "sharedPrePrep": "Chai spice mix",
    "primaryEquipment": "Gas / induction",
    "servingWare": "Chai glass",
    "targetPrice": 29,
    "ceilingPrice": 39,
    "availability": "All Day",
    "bestPairing": "Bun Makkhan / Vada Pav",
    "dietary": "Vegetarian",
    "proteinFocus": "Low",
    "spice": "Mild",
    "menuStatus": "Core",
    "notes": "Must be validated against actual vendor cost; target food cost must work at \u20b929."
  },
  {
    "id": "item-51",
    "name": "Adrak Chai",
    "categoryId": "cat-12",
    "price": 39,
    "description": "Everyday ginger chai.",
    "available": true,
    "isVeg": true,
    "isEgg": false,
    "isVegan": false,
    "isSpecial": false,
    "image": "/item-kulhadchai-arch.png",
    "subcategory": "Chai",
    "coreIngredients": "Tea, milk, sugar, ginger",
    "sharedPrePrep": "Crushed ginger / ginger prep",
    "primaryEquipment": "Gas / induction",
    "servingWare": "Chai glass",
    "targetPrice": 39,
    "ceilingPrice": 49,
    "availability": "All Day",
    "bestPairing": "Bhurji Pav / Toast",
    "dietary": "Vegetarian",
    "proteinFocus": "Low",
    "spice": "Mild",
    "menuStatus": "Core",
    "notes": null
  },
  {
    "id": "item-52",
    "name": "Reset Tea",
    "categoryId": "cat-12",
    "price": 59,
    "description": "Ginger, tulsi, lemongrass and citrus.",
    "available": true,
    "isVeg": true,
    "isEgg": false,
    "isVegan": true,
    "isSpecial": false,
    "image": "/item-kulhadchai-arch.png",
    "subcategory": "Tea",
    "coreIngredients": "Ginger, tulsi, lemongrass, citrus, water",
    "sharedPrePrep": "Herbal prep",
    "primaryEquipment": "Gas / induction",
    "servingWare": "Tea cup / glass",
    "targetPrice": 59,
    "ceilingPrice": 69,
    "availability": "All Day",
    "bestPairing": "Light breakfast / Salad",
    "dietary": "Vegan",
    "proteinFocus": "Low",
    "spice": "None",
    "menuStatus": "Core",
    "notes": null
  },
  {
    "id": "item-53",
    "name": "Masala Chaas",
    "categoryId": "cat-12",
    "price": 59,
    "description": "Yoghurt, roasted cumin, mint and spices.",
    "available": true,
    "isVeg": true,
    "isEgg": false,
    "isVegan": false,
    "isSpecial": false,
    "image": "/item-chaas-hero.png",
    "subcategory": "Chaas",
    "coreIngredients": "Yoghurt, water, cumin, mint, salt, spices",
    "sharedPrePrep": "Roast/grind cumin; mint prep",
    "primaryEquipment": "Blender / whisk",
    "servingWare": "Universal cold-drink glass",
    "targetPrice": 59,
    "ceilingPrice": 69,
    "availability": "All Day",
    "bestPairing": "Dal Chawal / Rajma",
    "dietary": "Vegetarian",
    "proteinFocus": "Medium",
    "spice": "Mild",
    "menuStatus": "Core",
    "notes": null
  },
  {
    "id": "item-54",
    "name": "Smoked Jeera Chaas",
    "categoryId": "cat-12",
    "price": 69,
    "description": "Buttermilk with roasted cumin and lightly smoky spice.",
    "available": true,
    "isVeg": true,
    "isEgg": false,
    "isVegan": false,
    "isSpecial": false,
    "image": "/item-chaas-hero.png",
    "subcategory": "Chaas",
    "coreIngredients": "Yoghurt, water, smoked/roasted cumin, herbs, salt",
    "sharedPrePrep": "Smoked cumin spice mix",
    "primaryEquipment": "Blender / whisk",
    "servingWare": "Universal cold-drink glass",
    "targetPrice": 69,
    "ceilingPrice": 79,
    "availability": "All Day",
    "bestPairing": "Khichdi / Bowl",
    "dietary": "Vegetarian",
    "proteinFocus": "Medium",
    "spice": "Mild",
    "menuStatus": "Core",
    "notes": null
  },
  {
    "id": "item-55",
    "name": "Chai + Bun Makkhan",
    "categoryId": "cat-13",
    "price": 99,
    "description": "Smol Chai with Bun Makkhan, Kanpur Se.",
    "available": true,
    "isVeg": true,
    "isEgg": false,
    "isVegan": false,
    "isSpecial": false,
    "image": "/items/bun_makkhan.jpg",
    "subcategory": "Combo",
    "coreIngredients": "Smol Chai + Bun Makkhan",
    "sharedPrePrep": "Use existing item prep",
    "primaryEquipment": "Existing stations",
    "servingWare": "Chai glass + side plate",
    "targetPrice": 99,
    "ceilingPrice": 109,
    "availability": "All Day",
    "bestPairing": "\u2014",
    "dietary": "Vegetarian",
    "proteinFocus": "Low",
    "spice": "Mild",
    "menuStatus": "Combo",
    "notes": null
  },
  {
    "id": "item-56",
    "name": "Chai + Vada Pav",
    "categoryId": "cat-13",
    "price": 109,
    "description": "Smol Chai with Vada Pav.",
    "available": true,
    "isVeg": true,
    "isEgg": false,
    "isVegan": false,
    "isSpecial": false,
    "image": "/items/vada_pav.jpg",
    "subcategory": "Combo",
    "coreIngredients": "Smol Chai + Vada Pav",
    "sharedPrePrep": "Use existing item prep",
    "primaryEquipment": "Existing stations",
    "servingWare": "Chai glass + side plate",
    "targetPrice": 109,
    "ceilingPrice": 119,
    "availability": "All Day",
    "bestPairing": "\u2014",
    "dietary": "Vegetarian",
    "proteinFocus": "Low-Medium",
    "spice": "Medium",
    "menuStatus": "Combo",
    "notes": null
  },
  {
    "id": "item-57",
    "name": "Chai + Chilli Cheese Toast",
    "categoryId": "cat-13",
    "price": 149,
    "description": "Smol Chai with Chilli Cheese Toast Fingers.",
    "available": true,
    "isVeg": true,
    "isEgg": false,
    "isVegan": false,
    "isSpecial": false,
    "image": "/item_panini.jpg",
    "subcategory": "Combo",
    "coreIngredients": "Smol Chai + Chilli Cheese Toast",
    "sharedPrePrep": "Use existing item prep",
    "primaryEquipment": "Existing stations",
    "servingWare": "Chai glass + side plate",
    "targetPrice": 149,
    "ceilingPrice": 159,
    "availability": "All Day",
    "bestPairing": "\u2014",
    "dietary": "Vegetarian",
    "proteinFocus": "Medium",
    "spice": "Medium",
    "menuStatus": "Combo",
    "notes": null
  },
  {
    "id": "item-58",
    "name": "Chai + Bhurji Pav",
    "categoryId": "cat-13",
    "price": 169,
    "description": "Smol Chai with Egg Bhurji Pav; paneer upgrade priced separately.",
    "available": true,
    "isVeg": false,
    "isEgg": true,
    "isVegan": false,
    "isSpecial": false,
    "image": "/items/bhurji_pav.jpg",
    "subcategory": "Combo",
    "coreIngredients": "Smol Chai + Egg Bhurji Pav",
    "sharedPrePrep": "Use existing item prep",
    "primaryEquipment": "Existing stations",
    "servingWare": "Chai glass + main plate",
    "targetPrice": 169,
    "ceilingPrice": 179,
    "availability": "All Day",
    "bestPairing": "\u2014",
    "dietary": "Egg",
    "proteinFocus": "High",
    "spice": "Medium",
    "menuStatus": "Combo",
    "notes": null
  },
  {
    "id": "item-59",
    "name": "Chai + Bombay Toastie",
    "categoryId": "cat-13",
    "price": 189,
    "description": "Smol Chai with Bombay Toastie.",
    "available": true,
    "isVeg": true,
    "isEgg": false,
    "isVegan": false,
    "isSpecial": false,
    "image": "/items/triple_decker.jpg",
    "subcategory": "Combo",
    "coreIngredients": "Smol Chai + Bombay Toastie",
    "sharedPrePrep": "Use existing item prep",
    "primaryEquipment": "Existing stations",
    "servingWare": "Chai glass + main plate",
    "targetPrice": 189,
    "ceilingPrice": 199,
    "availability": "All Day",
    "bestPairing": "\u2014",
    "dietary": "Vegetarian",
    "proteinFocus": "Low-Medium",
    "spice": "Medium",
    "menuStatus": "Combo",
    "notes": null
  }
];

// Helper for dynamic freshness
const today = new Date();
const formatDate = (daysOffset: number) => {
  const d = new Date();
  d.setDate(today.getDate() + daysOffset);
  return d.toISOString().split('T')[0];
};

export const initialInventoryItems: InventoryItem[] = [
  {
    id: 'inv-1',
    name: 'Potato',
    quantity: 10.0,
    unit: 'kg',
    category: 'Produce',
    minThreshold: 3.0,
    dateAdded: formatDate(-3),
    expiryDate: formatDate(7),
    status: 'fresh',
    notes: "Masala potato; crispy potatoes; vada filling | Uses: Triple Decker; Bombay Toastie; Vada Pav; Timur Potatoes; Conversation Board",
  },
  {
    id: 'inv-2',
    name: 'Mushroom',
    quantity: 10.0,
    unit: 'kg',
    category: 'Produce',
    minThreshold: 3.0,
    dateAdded: formatDate(-3),
    expiryDate: formatDate(7),
    status: 'fresh',
    notes: "Creamy garlic-herb mushroom base | Uses: Mushroom Omelette; Mushroom Decker; Mushroom & Herb Rice; Mushroom Salad; Mushroom Pizza; pasta add-on",
  },
  {
    id: 'inv-3',
    name: 'Chickpeas',
    quantity: 20.0,
    unit: 'kg',
    category: 'Pantry Grains',
    minThreshold: 5.0,
    dateAdded: formatDate(-3),
    expiryDate: formatDate(90),
    status: 'fresh',
    notes: "Cooked chickpeas; crispy chana; smashed chickpea | Uses: Protein Decker; Chana Bowl; Chana Salad; Loaded Papad; Conversation Board; sandwich side",
  },
  {
    id: 'inv-4',
    name: 'Paneer',
    quantity: 8.0,
    unit: 'kg',
    category: 'Dairy & Alternatives',
    minThreshold: 2.5,
    dateAdded: formatDate(-3),
    expiryDate: formatDate(3),
    status: 'fresh',
    notes: "Plain/crumble/marinated; creamy spread | Uses: Paneer Bhurji; Triple Decker spread; Protein Decker; Paneer Bowl; Paneer Pizza",
  },
  {
    id: 'inv-5',
    name: 'Yoghurt',
    quantity: 8.0,
    unit: 'kg',
    category: 'Dairy & Alternatives',
    minThreshold: 2.5,
    dateAdded: formatDate(-3),
    expiryDate: formatDate(3),
    status: 'fresh',
    notes: "Plain; mint yoghurt; herb yoghurt | Uses: Oats Bowl; bowls; salads; chaas; papad nachos; sides",
  },
  {
    id: 'inv-6',
    name: 'Rice',
    quantity: 20.0,
    unit: 'kg',
    category: 'Pantry Grains',
    minThreshold: 5.0,
    dateAdded: formatDate(-3),
    expiryDate: formatDate(90),
    status: 'fresh',
    notes: "Steamed rice; herbed rice | Uses: Dal Chawal; Rajma; Chana Bowl; Paneer Bowl; Mushroom Herb Rice; Khichdi",
  },
  {
    id: 'inv-7',
    name: 'Bread / Pav',
    quantity: 12.0,
    unit: 'loaves/pkts',
    category: 'Bakery',
    minThreshold: 4.0,
    dateAdded: formatDate(-3),
    expiryDate: formatDate(2),
    status: 'expiring_soon',
    notes: "Sandwich loaf + pav | Uses: Bun Makkhan; Bhurji Pav; Vada Pav; all sandwiches; toast fingers; Conversation Board",
  },
  {
    id: 'inv-8',
    name: 'Green Chutney',
    quantity: 10.0,
    unit: 'kg',
    category: 'Produce',
    minThreshold: 3.0,
    dateAdded: formatDate(-3),
    expiryDate: formatDate(7),
    status: 'fresh',
    notes: "Mint-coriander chutney | Uses: Triple Decker; Bombay Toastie; Vada Pav; sharing items",
  },
  {
    id: 'inv-9',
    name: 'Pickled Onion',
    quantity: 10.0,
    unit: 'kg',
    category: 'Produce',
    minThreshold: 3.0,
    dateAdded: formatDate(-3),
    expiryDate: formatDate(7),
    status: 'fresh',
    notes: "Quick pickle | Uses: Rajma; Paneer Bowl; salads; paneer pizza; papad nachos",
  },
  {
    id: 'inv-10',
    name: 'Tomato Base',
    quantity: 10.0,
    unit: 'kg',
    category: 'Produce',
    minThreshold: 3.0,
    dateAdded: formatDate(-3),
    expiryDate: formatDate(7),
    status: 'fresh',
    notes: "Tomato-onion / pizza-pasta base | Uses: Rajma; Pink Pasta; Margherita; Paneer Pizza",
  },
  {
    id: 'inv-11',
    name: 'Cucumber + Cabbage + Carrot',
    quantity: 10.0,
    unit: 'kg',
    category: 'Produce',
    minThreshold: 3.0,
    dateAdded: formatDate(-3),
    expiryDate: formatDate(7),
    status: 'fresh',
    notes: "Fresh crunch / slaw | Uses: Sandwiches; bowls; both salads; sides",
  },
  {
    id: 'inv-12',
    name: 'Corn',
    quantity: 10.0,
    unit: 'kg',
    category: 'Produce',
    minThreshold: 3.0,
    dateAdded: formatDate(-3),
    expiryDate: formatDate(7),
    status: 'fresh',
    notes: "Crispy corn + pizza lab | Uses: Crispy Corn; Pizza Lab (Bhutta); possible seasonal dishes",
  },
  {
    id: 'inv-13',
    name: 'Oats',
    quantity: 20.0,
    unit: 'kg',
    category: 'Pantry Grains',
    minThreshold: 5.0,
    dateAdded: formatDate(-3),
    expiryDate: formatDate(90),
    status: 'fresh',
    notes: "Breakfast + shake | Uses: Oats Fruit Bowl; Banana PB Oats Shake",
  },
  {
    id: 'inv-14',
    name: 'Seasonal Fruit',
    quantity: 10.0,
    unit: 'kg',
    category: 'Produce',
    minThreshold: 3.0,
    dateAdded: formatDate(-3),
    expiryDate: formatDate(7),
    status: 'fresh',
    notes: "One/two fruits only | Uses: Oats bowl; juice; seasonal shake; seasonal drink",
  },
  {
    id: 'inv-15',
    name: 'Citrus',
    quantity: 10.0,
    unit: 'kg',
    category: 'Produce',
    minThreshold: 3.0,
    dateAdded: formatDate(-3),
    expiryDate: formatDate(7),
    status: 'fresh',
    notes: "Juice, cordial, garnish | Uses: Lime soda; lemonade; iced tea; espresso tonic; Buransh Fizz; salads",
  },
  {
    id: 'inv-16',
    name: 'Ginger',
    quantity: 10.0,
    unit: 'kg',
    category: 'Produce',
    minThreshold: 3.0,
    dateAdded: formatDate(-3),
    expiryDate: formatDate(7),
    status: 'fresh',
    notes: "Fresh ginger / syrup | Uses: Adrak Chai; Reset Tea; seasonal drinks",
  },
  {
    id: 'inv-17',
    name: 'Buransh Cordial',
    quantity: 5.0,
    unit: 'litres',
    category: 'Beverage Bases',
    minThreshold: 1.5,
    dateAdded: formatDate(-3),
    expiryDate: formatDate(30),
    status: 'fresh',
    notes: "House/approved cordial | Uses: Buransh Fizz; seasonal experiment variations",
  },
  {
    id: 'inv-18',
    name: 'Jaggery Syrup',
    quantity: 5.0,
    unit: 'litres',
    category: 'Beverage Bases',
    minThreshold: 1.5,
    dateAdded: formatDate(-3),
    expiryDate: formatDate(30),
    status: 'fresh',
    notes: "Dissolved jaggery | Uses: Jaggery Latte; oats bowl sweetener; seasonal drinks",
  },
];

export const initialOrders: Order[] = [
  {
    id: 'ord-101',
    orderNumber: 'SMOL-101',
    items: [
      { id: 'oi-1', menuItemId: 'item-8', name: 'espresso', price: 79, quantity: 2 },
      { id: 'oi-2', menuItemId: 'item-1', name: 'bun makkhan, kanpur se', price: 79, quantity: 1 },
    ],
    subtotal: 237,
    discount: 0,
    tax: 11.85,
    total: 248.85,
    status: 'ready',
    paymentMethod: 'upi',
    orderType: 'dine_in',
    createdAt: new Date(Date.now() - 35 * 60000).toISOString(),
    updatedAt: new Date(Date.now() - 10 * 60000).toISOString(),
    cashierName: 'Priya',
  },
  {
    id: 'ord-102',
    orderNumber: 'SMOL-102',
    items: [
      { id: 'oi-3', menuItemId: 'item-55', name: 'smol chai', price: 29, quantity: 2 },
      { id: 'oi-4', menuItemId: 'item-7', name: 'the smol triple decker', price: 199, quantity: 1 },
    ],
    subtotal: 257,
    discount: 0,
    tax: 12.85,
    total: 269.85,
    status: 'preparing',
    paymentMethod: 'cash',
    orderType: 'dine_in',
    createdAt: new Date(Date.now() - 18 * 60000).toISOString(),
    updatedAt: new Date(Date.now() - 12 * 60000).toISOString(),
    cashierName: 'Priya',
  },
  {
    id: 'ord-103',
    orderNumber: 'SMOL-103',
    items: [
      { id: 'oi-5', menuItemId: 'item-50', name: 'jaggery sea-salt latte', price: 169, quantity: 1 },
      { id: 'oi-6', menuItemId: 'item-27', name: 'warm chocolate brownie', price: 149, quantity: 1 },
    ],
    subtotal: 318,
    discount: 0,
    tax: 15.9,
    total: 333.9,
    status: 'received',
    paymentMethod: 'upi',
    orderType: 'takeaway',
    createdAt: new Date(Date.now() - 4 * 60000).toISOString(),
    updatedAt: new Date(Date.now() - 4 * 60000).toISOString(),
    cashierName: 'Priya',
  },
];
